apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pipeline
  namespace: openshift-pipelines-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi