kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-pipelines-edit
  namespace: openshift-pipelines-example
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: openshift-pipelines-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-scc-rolebinding
  namespace: openshift-pipelines-example
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: openshift-pipelines-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole